// <auto-generated />
namespace EdeaDay.GestaoDeIdeias.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Comentarios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Comentarios));
        
        string IMigrationMetadata.Id
        {
            get { return "201305101933433_Comentarios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
