// <auto-generated />
namespace EdeaDay.GestaoDeIdeias.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ComentarioValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ComentarioValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201305210355198_ComentarioValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
